/**
 * MyViewController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface MyViewController : UIViewController 

/**
 * IBOutlet goalTextField
 */
@property (weak, nonatomic) IBOutlet UITextField *goalTextField;

/**
 * IBOutlet nextButton
 */
@property (weak, nonatomic) IBOutlet UIButton *nextButton;

/**
 * IBOutlet solutionTextView
 */
@property (weak, nonatomic) IBOutlet UITextView *solutionTextView;

/**
 * IBOutlet solveButton
 */
@property (weak, nonatomic) IBOutlet UIButton *solveButton;

/**
 * IBOutlet theoryButton
 */
@property (weak, nonatomic) IBOutlet UIButton *theoryButton;

/**
 * IBOutlet theoryTextView
 */
@property (weak, nonatomic) IBOutlet UITextView *theoryTextView;

/**
 * IBOutlet warningsTextView
 */
@property (weak, nonatomic) IBOutlet UITextView *warningsTextView;

/**
 * IBAction getNextSolution
 * Selector: getNextSolution
 */
-(IBAction) getNextSolution;

/**
 * IBAction hideKeyboard
 * Selector: hideKeyboard
 */
-(IBAction) hideKeyboard;

/**
 * IBAction setTheory
 * Selector: setTheory
 */
-(IBAction) setTheory;

/**
 * IBAction solve
 * Selector: solve
 */
-(IBAction) solve;

@end
